apiVersion: apps/v1
kind: Deployment
metadata:
  name: hare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animal
      type: hare
  template:
    metadata:
      labels:
        app: animal
        type: hare
    spec:
      containers:
        - image: "supergiantkir/animals:hare"
          name: hare
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animal
      type: bear
  template:
    metadata:
      labels:
        app: animal
        type: bear
    spec:
      containers:
        - image: "supergiantkir/animals:bear"
          name: bear
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: animal-service
spec:
  selector:
    app: animal
  ports:
    - name: aport
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
