--- 
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: hello
spec: 
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
            - 
              command: 
                - echo
                - James
              image: "alpine:latest"
              imagePullPolicy: IfNotPresent
              name: hello
          restartPolicy: OnFailure
  schedule: "0 8 * * *"
