apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: spring-music
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
   
